---
include:
  # Default build - Standard split keyboard mode (left central, right peripheral)
  # ZMK Studio enabled by default in all firmware

  # Left half (central/master) with ZMK Studio support
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: eyelash_sofle_left

  # Right half (peripheral) with ZMK Studio support
  - board: eyelash_sofle_right
    shield: nice_view_custom
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: eyelash_sofle_right

  # Universal settings reset firmware (works for all boards)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
