---
include:
  # STANDARD MODE - Custom board approach (left central + right peripheral)

  # Left half (central/master with Studio support)
  - board: eyelash_sofle_left
    shield: nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_standard_left_central

  # Right half (peripheral for standard mode)
  - board: eyelash_sofle_right
    shield: nice_oled
    artifact-name: sofle_standard_right_peripheral

  # DONGLE MODE - Shield approach with nice_nano_v2 + bongo cat display

  # Dongle (central receiver with bongo cat display)
  - board: nice_nano_v2
    shield: eyelash_sofle_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_dongle_central

  # Left half (peripheral for dongle mode)
  - board: nice_nano_v2
    shield: eyelash_sofle_peripheral_left nice_oled
    artifact-name: sofle_dongle_left_peripheral

  # Right half (peripheral for dongle mode)
  - board: nice_nano_v2
    shield: eyelash_sofle_peripheral_right nice_oled
    artifact-name: sofle_dongle_right_peripheral

  # UNIVERSAL SETTINGS RESET

  # Settings reset firmware (works for all boards/shields)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
