---
include:
  # Standard wireless mode (fallback)
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: eyelash_sofle_standard_left
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: eyelash_sofle_standard_right

  # ZMK Studio mode (preserves your current setup)
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left

  # Dongle mode with zmk-dongle-display
  - board: nice_nano_v2
    shield: dongle_display
    artifact-name: eyelash_sofle_dongle_central

  # Settings reset utilities
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset_left
  - board: eyelash_sofle_right
    shield: settings_reset
    artifact-name: settings_reset_right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_dongle
