---
include:
  # STANDARD MODE - Left central + Right peripheral

  # Left half (central/master with Studio support)
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: sofle_standard_left_central

  # Right half (peripheral for standard mode)
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: sofle_standard_right_peripheral

  # DONGLE MODE - Dongle central + Left peripheral + Right peripheral

  # Dongle (central receiver with Studio support - TEST WITH NICE_VIEW FIRST)
  - board: eyelash_sofle_dongle
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2 -DCONFIG_BT_MAX_CONN=7 -DCONFIG_BT_MAX_PAIRED=7 -DCONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
    artifact-name: sofle_dongle_central

  # Left half (peripheral for dongle mode)
  - board: eyelash_sofle_left
    shield: nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_dongle_left_peripheral

  # Right half (peripheral for dongle mode)
  - board: eyelash_sofle_right
    shield: nice_view_custom
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_dongle_right_peripheral

  # UNIVERSAL SETTINGS RESET

  # Settings reset firmware (works for all boards)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
